{% set name = "laptrack" %}
{% set version = "0.17.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/laptrack-{{ version }}.tar.gz
  sha256: b72e73b6ce985d042647970bc965fac99166c9e203e38aa65410d86557579a06

build:
  entry_points:
    - laptrack = laptrack.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.10,<3.14
  run:
    - click >=8.0.1,<9.0.0
    - python >=3.10,<3.14
    - networkx >=3.4.2,<3.0.0
    - numpy >=1.26.0,<3.0.0
    - pandas >=1.3.1,<3.0.0
    - pooch >=1.6.0,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - scikit-image >=0.24.0,<1.0.0
    - scikit-learn >=1.5.0,<2.0.0
    - scipy >=1.14.0,<1.15.0
    - typing-extensions >=4.1.0,<5.0.0
test:
  imports:
    - laptrack
  commands:
    - pip list
    - pip check
    - laptrack --help
  requires:
    - python 3.11
    - pip

about:
  home: https://github.com/yfukai/laptrack
  summary: |
    Provides a robust particle tracking algorithm using the Linear
    Assignment Problem, with various cost functions for linking.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - goanpeca
    - yfukai
