{% set name = "laptrack" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/laptrack-{{ version }}.tar.gz
  sha256: e31799cf7e501c94dc3f28f091d8e7a4207992238d8d443b983644142aa347da

build:
  entry_points:
    - laptrack = laptrack.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8,<3.12
  run:
    - click >=8.0.1,<9.0.0
    - python >=3.8,<3.12
    - networkx >=2.6.1,<3.0.0
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.1,<2.0.0
    - pooch >=1.6.0,<2.0.0
    - pydantic >=1.10.2,<2.0.0
    - scikit-image >=0.19.3,<0.21.0
    - scipy >=1.8.0,<2.0.0
    - typing-extensions >=4.1.0,<5.0.0

test:
  imports:
    - laptrack
  commands:
    - pip list
    - pip check
    - laptrack --help
  requires:
    - pip

about:
  home: https://github.com/yfukai/laptrack
  summary: |
    Provides a robust particle tracking algorithm using the Linear
    Assignment Problem, with various cost functions for linking.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - goanpeca
    - yfukai
