{% set name = "laptrack" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/laptrack-{{ version }}.tar.gz
  sha256: 8ae7c682de5bb882ace4896514a49ccb1cc426f9d6bc92e7fad0f435bbd80dab

build:
  entry_points:
    - laptrack = laptrack.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7,<3.11
  run:
    - click >=8.0.1,<9.0.0
    - python >=3.7,<3.11
    - networkx >=2.6.1,<3.0.0
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.1,<2.0.0
    - pooch >=1.6.0,<2.0.0
    - pydantic >=1.10.2,<2.0.0
    - scikit-image >=0.19.3,<0.20.0
    - scipy >=1.7.0,<2.0.0
    - typing-extensions >=4.1.0,<5.0.0

test:
  imports:
    - laptrack
  commands:
    - pip list
    - pip check
    - laptrack --help
  requires:
    - pip

about:
  home: https://github.com/yfukai/laptrack
  summary: |
    Provides a robust particle tracking algorithm using the Linear
    Assignment Problem, with various cost functions for linking.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - goanpeca
    - yfukai
